services:
  db:
    image: mariadb:latest
    container_name: wordpress-db
    restart: unless-stopped
    env_file:
      - ./example.env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network

  wordpress:
    image: wordpress:latest
    container_name: wordpress-app
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - ./example.env
    ports:
      - "8080:80"
    volumes:
      - wp_data:/var/www/html
    networks:
      - wordpress_network

volumes:
  db_data:
  wp_data:

networks:
  wordpress_network:

